### ISSUE TITLE
' (prime character) in field label translated to invalid java code

### ISSUE THREAD

**Issue by mabre** [Frege/frege#284]
The following code compiles with frege 3.23.451, but 3.24.100 produces invalid java code:

``` haskell
module PrimeGetter where

data Generic' c = Generic' { unGeneric' :: Maybe c }
```

```
calling: javac -cp /home/markus/Downloads/frege/frege3.24.100.jar:. -d . -sourcepath . -encoding UTF-8 ./PrimeGetter.java 
./PrimeGetter.java:114: error: unclosed character literal
    mem$unGeneric' = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
                 ^
./PrimeGetter.java:114: error: not a statement
    mem$unGeneric' = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
    ^
./PrimeGetter.java:122: error: unclosed character literal
  final public Lazy<PreludeBase.TMaybe<𝓒>> mem$unGeneric'  ;
                                                         ^
./PrimeGetter.java:150: error: unclosed character literal
              Thunk.<PreludeBase.TMaybe<β>>nested((Lazy<Lazy<PreludeBase.TMaybe<β>>>)(() -> arg$2.apply(arg$1.mem$unGeneric')))
                                                                                                                           ^
./PrimeGetter.java:154: error: unclosed character literal
    final PreludeBase.TMaybe<α> a1$7581 = arg$1.mem$unGeneric'.call();
                                                             ^
5 errors
E PrimeGetter.hs:3: java compiler errors are most likely
    caused by erroneous native definitions
```
