### PR TITLE
Fix #284: Mangle named fields for Java

### LINKED ISSUE #284: ' (prime character) in field label translated to invalid java code
The following code compiles with frege 3.23.451, but 3.24.100 produces invalid java code:

``` haskell
module PrimeGetter where

data Generic' c = Generic' { unGeneric' :: Maybe c }
```

```
calling: javac -cp /home/markus/Downloads/frege/frege3.24.100.jar:. -d . -sourcepath . -encoding UTF-8 ./PrimeGetter.java 
./PrimeGetter.java:114: error: unclosed character literal
    mem$unGeneric' = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
                 ^
./PrimeGetter.java:114: error: not a statement
    mem$unGeneric' = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
    ^
./PrimeGetter.java:122: error: unclosed character literal
  final public Lazy<PreludeBase.TMaybe<𝓒>> mem$unGeneric'  ;
                                                         ^
./PrimeGetter.java:150: error: unclosed character literal
              Thunk.<PreludeBase.TMaybe<β>>nested((Lazy<Lazy<PreludeBase.TMaybe<β>>>)(() -> arg$2.apply(arg$1.mem$unGeneric')))
                                                                                                                           ^
./PrimeGetter.java:154: error: unclosed character literal
    final PreludeBase.TMaybe<α> a1$7581 = arg$1.mem$unGeneric'.call();
                                                             ^
5 errors
E PrimeGetter.hs:3: java compiler errors are most likely
    caused by erroneous native definitions
```

### PR DESCRIPTION
**Pull request by matil019**
Fixes #284 

This PR fixes #284 by mangling named fields of records type so that they have valid names in generated Java files.

`frege.compiler.gen.java.Common.namedFields` appears to be used in the following places:

- `frege.compiler.gen.java.Common.mkMember` for Java field declarations
- `frege.compiler.gen.java.DataCode.conDecls` for assignments in Java constructors
- `frege.compiler.gen.java.Match.match` for field accesses

At all of the places, name mangling is needed. This PR modifies `namedFields` itself to fix them all.

### CODE REVIEW

**Comment by matil019** [comment]
Sure. I'll add another `comp` test module that tests using an imported record, and some `qc` tests to see updating, changing, etc. really work.

FYI, here's the diff of generated Java code before and after the change:

```Issue284.java.patch
--- a/tests/comp/Issue284.java	2018-03-11 17:51:08.837713437 +0900
+++ b/tests/comp/Issue284.java	2018-03-11 17:51:01.548772702 +0900
@@ -1,7 +1,7 @@
 /*
   Source code is in UTF-8 encoding. The following symbols may appear, among others:
   α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
-  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.319
+  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.321
   from ./tests/comp/Issue284.fr Do not edit this file! Instead, edit the source file and recompile.
 */
 
@@ -31,7 +31,7 @@
 
 @SuppressWarnings("unused")
 @Meta.FregePackage(
-  source="./tests/comp/Issue284.fr", time=1520758268668L, jmajor=1, jminor=8,
+  source="./tests/comp/Issue284.fr", time=1520758261373L, jmajor=1, jminor=8,
   doc=" https://github.com/Frege/frege/issues/284 Issue 284   ",
   imps={
     "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeIO",
@@ -114,7 +114,7 @@
   implements frege.runtime.Value, Lazy<TGeneric$tick<𝓒>>, Kind.U<TGeneric$tick<?>, 𝓒>
  {
   private TGeneric$tick(final Lazy<PreludeBase.TMaybe<𝓒>> arg$1) {
-    mem$unGeneric' = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
+    mem$unGeneric$tick = Thunk.<PreludeBase.TMaybe<𝓒>>shared(arg$1);
   }
   final public int constructor() {
     return 0;
@@ -122,7 +122,7 @@
   final public static <𝓒> TGeneric$tick<𝓒> mk(final Lazy<PreludeBase.TMaybe<𝓒>> arg$1) {
     return new TGeneric$tick<𝓒>(arg$1);
   }
-  final public Lazy<PreludeBase.TMaybe<𝓒>> mem$unGeneric'  ;
+  final public Lazy<PreludeBase.TMaybe<𝓒>> mem$unGeneric$tick  ;
   final public TGeneric$tick<𝓒> call() {
     return this;
   }
@@ -150,11 +150,13 @@
     final TGeneric$tick<α> arg$1, final Func.U<PreludeBase.TMaybe<α>, PreludeBase.TMaybe<β>> arg$2
   ) {
     return TGeneric$tick.<β>mk(
-              Thunk.<PreludeBase.TMaybe<β>>nested((Lazy<Lazy<PreludeBase.TMaybe<β>>>)(() -> arg$2.apply(arg$1.mem$unGeneric')))
+              Thunk.<PreludeBase.TMaybe<β>>nested(
+                    (Lazy<Lazy<PreludeBase.TMaybe<β>>>)(() -> arg$2.apply(arg$1.mem$unGeneric$tick))
+                  )
             );
   }
   final public static <α> PreludeBase.TMaybe<α> unGeneric$tick(final TGeneric$tick<α> arg$1) {
-    final PreludeBase.TMaybe<α> a1$7592 = arg$1.mem$unGeneric'.call();
+    final PreludeBase.TMaybe<α> a1$7592 = arg$1.mem$unGeneric$tick.call();
     return a1$7592;
   }
 }
```

**Comment by matil019** [comment]
@Ingo60 Done.

Along the way, I found that `make test` skips a property if it has a tick in its name e.g. 
```
java.lang.NoSuchFieldException: p_matchMangled' while checking property tests.qc.Record.p_matchMangled'
```

I'll leave that because I think this is another issue.

**Comment by Ingo60** [comment]
Yes, it looks like the QuickCheck tool doesn't mangle names at all. The same should happen for a property you give an operator name, i.e.

     (°°°) = property ...

I shall look into that and fix it right after merging this.
